"""Added all MusicPlatform tables

Revision ID: 31b3b5f42727
Revises: 
Create Date: 2025-12-23 19:40:30.502627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b3b5f42727'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genius_id', sa.Integer(), nullable=True),
    sa.Column('parse_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genius_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('spotify_song_id', sa.String(), nullable=False),
    sa.Column('artists', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.genius_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_song_id')
    )
    op.create_table('user_liked_artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('liked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.genius_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lyrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track.spotify_song_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('bpm', sa.String(), nullable=True),
    sa.Column('camelot', sa.String(), nullable=True),
    sa.Column('popularity', sa.String(), nullable=True),
    sa.Column('energy', sa.String(), nullable=True),
    sa.Column('danceability', sa.String(), nullable=True),
    sa.Column('happiness', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track.spotify_song_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_liked_track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('liked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track.spotify_song_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_liked_track')
    op.drop_table('track_details')
    op.drop_table('lyrics')
    op.drop_table('user_liked_artist')
    op.drop_table('track')
    op.drop_table('user')
    op.drop_table('artist')
    # ### end Alembic commands ###
