"""Renamed columns in track_details and lyrics

Revision ID: 4b1f0bed7981
Revises: 31b3b5f42727
Create Date: 2025-12-23 19:56:57.431281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1f0bed7981'
down_revision: Union[str, None] = '31b3b5f42727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lyrics', sa.Column('spotify_song_id', sa.String(), nullable=False))
    op.drop_constraint('lyrics_track_id_fkey', 'lyrics', type_='foreignkey')
    op.create_foreign_key(None, 'lyrics', 'track', ['spotify_song_id'], ['spotify_song_id'])
    op.drop_column('lyrics', 'track_id')
    op.add_column('track_details', sa.Column('spotify_song_id', sa.String(), nullable=False))
    op.drop_constraint('track_details_track_id_fkey', 'track_details', type_='foreignkey')
    op.create_foreign_key(None, 'track_details', 'track', ['spotify_song_id'], ['spotify_song_id'])
    op.drop_column('track_details', 'track_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_details', sa.Column('track_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'track_details', type_='foreignkey')
    op.create_foreign_key('track_details_track_id_fkey', 'track_details', 'track', ['track_id'], ['spotify_song_id'])
    op.drop_column('track_details', 'spotify_song_id')
    op.add_column('lyrics', sa.Column('track_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lyrics', type_='foreignkey')
    op.create_foreign_key('lyrics_track_id_fkey', 'lyrics', 'track', ['track_id'], ['spotify_song_id'])
    op.drop_column('lyrics', 'spotify_song_id')
    # ### end Alembic commands ###
